#!/usr/bin/env python2
import os
import sys
import time

exploit = []
exploit.append('')

#Append your exploit name

tick_interval = 30
#set tick interval time


while True:
    for i in exploit:
        os.system('python ' + i)
    print '------------------------------------------tick-----------------------------------------'
    time.sleep(tick_interval)
